return {
    "Normal Seed Pack",
    "Exotic Seed Pack",
    "Basic Seed Pack",
    "Gourmet Seed Pack",
    "Exotic Gourmet Seed Pack",
    "Rainbow Exotic Gourmet Seed Pack",
    "Sprout Seed Pack",
    "Exotic Sprout Seed Pack",
    "Rainbow Exotic Sprout Seed Pack",
    "Silver Legendary Seed Pack",
    "Silver Mythical Seed Pack",
    "Silver Divine Seed Pack",
    "Silver Prismatic Seed Pack",
    "Skyroot Chest",
    "Safari Seed Pack",
    "Exotic Safari Seed Pack",
    "Rainbow Exotic Safari Seed Pack",
    "Flower Seed Pack",
    "Exotic Flower Seed Pack",
    "Rainbow Exotic Flower Seed Pack",
    "Fall Seed Pack",
    "Silver Fall Seed Pack",
    "Exotic Fall Seed Pack",
    "Rainbow Exotic Fall Seed Pack",
    "Zen Seed Pack",
    "Exotic Zen Seed Pack",
    "Rainbow Exotic Zen Seed Pack",
    "Summer Seed Pack",
    "Exotic Summer Seed Pack",
    "Rainbow Exotic Summer Seed Pack",
    "Ancient Seed Pack",
    "Rainbow Exotic Enchanted Seed Pack",
    "Gardener Seed Pack",
    "Exotic Crafters Seed Pack",
    "Rainbow Exotic Crafters Seed Pack",
    "Enchanted Seed Pack",
    "Exotic Enchanted Seed Pack",
    "Prime Seed Pack",
    "Exotic Prime Seed Pack",
    "Zenith Seed Pack",
    "Exotic Zenith Seed Pack"
}
